---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ssh-operator.lcpu.dev
  resources:
  - sshauthorizedkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ssh-operator.lcpu.dev
  resources:
  - sshkeypairs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ssh-operator.lcpu.dev
  resources:
  - sshkeypairs/finalizers
  verbs:
  - update
- apiGroups:
  - ssh-operator.lcpu.dev
  resources:
  - sshkeypairs/status
  verbs:
  - get
  - patch
  - update
