# permissions for end users to view sshauthorizedkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ssh-operator
    app.kubernetes.io/managed-by: kustomize
  name: sshauthorizedkey-viewer-role
rules:
- apiGroups:
  - ssh-operator.lcpu.dev
  resources:
  - sshauthorizedkeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ssh-operator.lcpu.dev
  resources:
  - sshauthorizedkeys/status
  verbs:
  - get
