# permissions for end users to view sshkeypairgenerations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ssh-operator
    app.kubernetes.io/managed-by: kustomize
  name: sshkeypairgeneration-viewer-role
rules:
- apiGroups:
  - ssh-operator.lcpu.dev
  resources:
  - sshkeypairgenerations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ssh-operator.lcpu.dev
  resources:
  - sshkeypairgenerations/status
  verbs:
  - get
