# permissions for end users to edit sshkeypairgenerations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ssh-operator
    app.kubernetes.io/managed-by: kustomize
  name: sshkeypairgeneration-editor-role
rules:
- apiGroups:
  - ssh-operator.lcpu.dev
  resources:
  - sshkeypairgenerations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ssh-operator.lcpu.dev
  resources:
  - sshkeypairgenerations/status
  verbs:
  - get
